### ISSUE TITLE
Unaccounted Run States in `resource_run` -> `waitForRun()`

### ISSUE THREAD

**Issue by jeffwecan** [mitchellh/terraform-provider-multispace#3] opened 2021-10-19 18:16 UTC
Depending on the specific TFE/TFC organization and/or workspace settings, it appears that `resource_run` may attempt invalid run transitions. That is, it attempts to apply a run when an apply is not an available action. For example, when the workspace targeted by `resource_run` has with cost estimation enabled and the run's plan is finished:

```shellsession
-----------------------------------------------------: timestamp=2021-10-19T13:05:38.006-0500
2021-10-19T13:05:38.007-0500 [INFO]  provider.terraform-provider-multispace_v0.1.0: 2021/10/19 13:05:38 [DEBUG] non-progressive state, exiting "cost_estimating": timestamp=2021-10-19T13:05:38.007-0500
2021-10-19T13:05:38.007-0500 [INFO]  provider.terraform-provider-multispace_v0.1.0: 2021/10/19 13:05:38 [INFO] plan complete, confirming apply. "<some-run-id>": timestamp=2021-10-19T13:05:38.007-0500
2021-10-19T13:05:38.008-0500 [INFO]  provider.terraform-provider-multispace_v0.1.0: 2021/10/19 13:05:38 [DEBUG] TFE API Request Details:
---[ REQUEST ]---------------------------------------
POST /api/v2/runs/<some-run-id>/actions/apply HTTP/1.1
Host: app.terraform.io

< ... >

{
 "data": {
  "type": "",
  "attributes": {
   "comment": "terraform-provider-multispace on Tue Oct 19 13:05:38 CDT 2021"
  }
 }
}

-----------------------------------------------------: timestamp=2021-10-19T13:05:38.008-0500
multispace_run.certificates: Still creating... [4m40s elapsed]
2021-10-19T13:05:38.059-0500 [TRACE] dag/walk: vertex "multispace_run.infrastructure" is waiting for "multispace_run.certificates"
2021-10-19T13:05:38.080-0500 [INFO]  provider.terraform-provider-multispace_v0.1.0: 2021/10/19 13:05:38 [DEBUG] TFE API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 409 Conflict

<...>

{
 "errors": [
  {
   "status": "409",
   "title": "transition not allowed"
  }
 ]
}
-----------------------------------------------------: timestamp=2021-10-19T13:05:38.080-0500
2021-10-19T13:05:38.083-0500 [TRACE] maybeTainted: multispace_run.certificates encountered an error during creation, so it is now marked as tainted

<...>
╷
│ Error: transition not allowed
│ 
│   with multispace_run.certificates,
│   on integration_tests.tf line 33, in resource "multispace_run" "certificates":
│   33: resource "multispace_run" "certificates" {
│ 
╵
2021-10-19T13:05:38.129-0500 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021-10-19T13:05:38.131-0500 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-10-19T13:05:38.132-0500 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
```

and the tl;dr version of those debug logs:

```shellsession
non-progressive state, exiting "cost_estimating": timestamp=2021-10-19T13:05:38.007-0500
plan complete, confirming apply. "<some-run-id>": timestamp=2021-10-19T13:05:38.007-0500
Error: transition not allowed
```

I'm unclear on what the TFC API maintainers would consider the canonical method for determing when a run is ready to receive an apply action request. Perhaps the `actions` attribute on the workspace run would be a better fit? This `is-confirmable` key in particular:

```json
{
 "data": {
  "id": "<some-run-id>",
  "type": "runs",
  "attributes": {
   "actions": {
    "is-cancelable": true,
    "is-confirmable": false,
    "is-discardable": false,
    "is-force-cancelable": false
   },
   # ...
}
```

Anywho, I would be happy to try submitting a patch along these lines at some point but figured I would lodge an issue on the matter in the meantime. 😄

**Comment by lucymhdavies** [comment] 2021-11-23 12:03
Looks like my issue is a duplicate of this.

Was looking into it myself, and have what looks like a fix:
https://github.com/lucymhdavies/terraform-provider-multispace/commit/d44e04b4899f69655a2d6e6dc2b6c69d76799542

Needs some tweaks for if a workspace enters a RunPolicySoftFailed state.
It's debatable as to whether the correct action in that case would be to wait for human approval, or just proceed. Arguably something which should be configurable.

I'll raise a PR now in its current state, and @mitchellh can determine the best option.

**Comment by mitchellh** [comment] 2021-11-23 17:34
Hello! Sorry, I for some reason didn't get (or missed) the email notification about this issue, but luckily I saw @lucymhdavies response. Thank you for the PR, I'll cut this release with that change now. I'm not surprised I missed this, I was actually pretty sure at the time of implementation I did, but I didn't have those states available to test. :)

**Comment by mitchellh** [comment] 2021-11-23 17:35
Fixed thanks to @lucymhdavies

**Closed by mitchellh** 2021-11-23 17:35 UTC

**Comment by mitchellh** [comment] 2021-11-23 17:49
By the way I cut version 0.1.1, its building and releasing as I speak.
